controller:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    annotations:
      metallb.universe.tf/address-pool: default-pool
      metallb.universe.tf/loadBalancerIPs: 10.0.0.11