---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCgMRHbGFdenIwR6p1wqAnQjTiqFZRwJUk74jJaDwbv5AcpQdPS9OgGUnf+rjXbT3/jN9lNVP879vxeo39uaa9yLddvTm0KoINyo2WxAb31S+Sw4FxdtKmwGK3xgetaptuZOXU7FI5Eo83/EaHpFxAl+O0aTUVbLCcMpZPBkCOb5P0T5FNs3qhjcPdSUotzMXdGsI7e9urgSHEFY8gwQOg/zEpaoQIcG7FxrPNU5gsqUFmS31/0V9jIXKUmAiFt2PTDXoa8tOazRH8Zb7MWdb4RzRF52SSl7s+Jnnvji1+MjEHhEk5w092skV/WtlaxFZE6etpGrUmOV9Uc3hHya1QGk7UuBKvyAbnKxbBe4CzI1XLtgm8XfNI+TLF6NrmnKeIZP61Z4NsDgbSCOv/u9TygZt/dgUJ4HZuDpbqf675LuvuIXPrVz1KpA1z09q1n60MSsvs00RcufUCCoOXZMqGP+v/4yt4VcUDQovGr82Hm8s+jqiUslHm6w+N+09C90AfIq53D8uPsOMTmwnc0v2gyChA+03T1ucsjkIpZ4LNPiBbk0oD//vDM5uzNEzXziOsPf/F4M4QVMk0RCK08x3mm2AKVU2xukjkNXWFPMNaqFMZnI/4qd7Y8bCIldj/Ny80VppFmaHOO5b2qtp+0448ZWleUBFQaXdZ5GW6k6JnHPBER++PjDkn6Q4JGphfz0GtViLWL3x+cHL/quFo0gQhULcdYkU0XlSF9xS0VrU7E+glpu2l1AedtbHq45gUqhYy98WqdWWgncpvoL6LlssgpXoNH+/orBR5QZCJcAbVPR1KAYB25iQRGSSFOZNDtLgXYN0fixxB5DaOXoC4jWeOIX5SXRgg+rpccIG0RfCeeMHXzZ9dNJ6TmU8E=
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
