---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCoNyjO3W8VIA/poX6zKYUdgWKDylvy6gGNMXyEjPMgpJwrxkSSAVs2/+x3TUS4t49zy+lYKQRmUzjZI2eAC+mBXsOKPFzX8AIyXoxzxVqz0yUi5919E53ZxLvXvpanZj6W6Ip1cqUMxwcL53Xkv1QmHgunBmPRKRFLU0DsuGVPRIhXWSdjyTBTkak4faoINnYrUph7WZr1xmhv6r25JkqoU+91bLBXfH7MqJqfCge9KsGwIDCWrlgzg2Cveml0+iOQERlIiG2WEWHD0TU5pByJRRdbK/VUVQIdSRI3Bf4KiEnE9s2l2VFAitfnasUllstJgfIWXhqq6fL2BXgWcnXWMoE/sqcf4eG5Jjy/KdYE3pbwOG03b1Un82NaYOkC0N0JZgp3Hg48c+ruLJdly4jnTW6qNkRwpUBBxTNLx0exmOXCNoWVg6eSepIzg/omsMUByT09neUb/3nlcxMismj/DiEA/JQ9Syu4TE3Mz9LQqi7CDY+AVigiGheYltrBHbCkeltETTsZxXUAWtk3yDviYnNDh+KBLebAFa1kJEdbZhr1tE5jJsCi3NFkAq4Bp9lUTTHewDa4Q47AUMg+6Fqw3xpgtlEuDrvoveiYZACpei4kyTSaOoDjoV2ejby6HOHoEa07vQMD3uVHvy+kM2ZWn55ysy9IqnBJo1GboSnIX2pLQ2pC1SRXi6yTab6EJN6+pxzG6kKORNDuH5fI7sycEUY4toJEVCxiQwhgqypAz9LBUrGC0lTNXgrXIeASwVcRdAhzQ3jKIEk+92Y7rX3pxL3sOxIzqykulC3ExK2PqKNteyWDxhoGHti9v1EcEa3xKX4A789LsqrnJE6Cx/jWwn6yKrq4GwlimpIXazVRcK5gJunzT1FNlokp/g/fu36lUd7YtB4Ee8yHqpUoY4ao+gMo6OdzB4oK4djgpMQjjDta/w3YPRUf
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
