---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCXYCkh1pkNEgrfTBAH2HX8N+b+Ag9dWERa1eIQ8uNm0zayCkNA/5HEdS7HSfWpfGz8oG8knuIG8lh9xXV1BcL7GfmgaGBvw4WPq0ZlsVxPwptaN+JpwYxTmTUenXZmZF1a4Z6wDMYtyDdGDLDShq0MjECrDANSJpfKQThdRsz2yyBGdv0/wuveUveDVqUiaZrEfSNtw7G8SfcDTrd7Ds+VDGP16T4sUu5Oebf9YRWu3VyOyUNEEdgNhY3z/EFfOVoGleht/Qmu5cVMCIK9HkLLZcgUjc+3mgJS5qrATC4ouu1kXHNRcMXL46/PzY5y+AJ4iRgrgibpcnfn5MY+kfZppHiBc3XRDrl5ISBniTosez/Iom0Oziv7w8d+1VY52yqkz65Ic4z2gtzYxSmC59+uB1inkFGepDqpBcrCIIcJI5F3TV2kPz53yoz2dSoT/82Pyo3soQZSr8gz2dEb6o+52M3ItaMr+YZWkSWSBxnNQPdlin7npG4RAElXEoTGYafT/t3ErSi+SAtizwCkS0Smxq1bHebn+pbs+CtNfe9uQ+FqADoBhhtbOUcqzKRq8kwMYUIBR3qLk0WqSDyO9XIUQBYB8h0b7CXNIMedNka7x10jK7N0kS8TtHdriQ2iDVOpTlj0Zje881SZf4k4YcykWBD1rF8MxFsy1msRiHWL/evs+/RZnR1SBb6i2nV/bycvYfNWzyjaHKy5VIfoMFdAf2UoAe5dU3Fy0jsCPaIFzK33wReVe9sSqn0ky288muPuetm3na4sj/NvGM30oNa6mTLz+W5ZwQr2Ul2J4H8uTP+cx5/D61NSD5r5YHhNRa+lOzo5iGEAQLvPbfCEo8V4hHYzM6vkHHZTL1QM6/1IUpghcMbYiYqu+5I=
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
