apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production-cert
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: letsencrypt-production-secret
  dnsNames:
  - homelab.com