apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pe-engineering-hackathon
  namespace: argocd
spec:
  destination:
    namespace: pe-engineering-hackathon
    server: https://kubernetes.default.svc
  project: operators
  source:
    path: ./helm
    repoURL: https://github.com/nic5694/PaneraBreadWarriors
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---