apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: "https://argocd.local" # updated to match ingress host and TLS

  # Use this section to configure an external OIDC provider (no Dex)
  oidc.config: |
    name: homelab-oidc
    issuer: https://example-oidc-provider.example.com
    clientID: YOUR_CLIENT_ID
    clientSecret: $oidc.homelab.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
    enablePKCEAuthentication: true
    # enableUserInfoGroups: true
    # userInfoPath: /userinfo

  # Optional: restrict CLI client ID (if your provider requires separate client)
  # cliClientID: YOUR_CLI_CLIENT_ID
