apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflare
  name: cloudflare
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  strategy: {}
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      containers:
      - image: cloudflare/cloudflared:1895-8679787525ed
        name: cloudflared
        resources: {}
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-secret
              key: token
status: {}
