apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: headless-fedora
  namespace: homelab-vms
  annotations:
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    argocd.argoproj.io/sync-wave: "7"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: headless-fedora
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          interfaces:
          - name: default
            masquerade: {}
          - name: physical-nic
            bridge: {}
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
      networks:
      - name: default
        pod: {}
      - name: physical-nic
        multus:
          networkName: homelab-vms/physical-network
      volumes:
      - name: rootdisk
        containerDisk:
          # Swap to quay.io/containerdisks/ubuntu:22.04 for Ubuntu.
          image: quay.io/containerdisks/fedora:40
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            users:
              - name: cloud-user
                lock_passwd: false
                sudo: ALL=(ALL) NOPASSWD:ALL
            chpasswd:
              expire: false
              list: |
                cloud-user:dummy1234
            ssh_pwauth: true
            disable_root: false
          networkData: |-
            version: 2
            ethernets:
              eth1:
                dhcp4: false
                addresses:
                  - 192.168.0.210/24
                gateway4: 192.168.0.1
                nameservers:
                  addresses:
                    - 192.168.0.242