---
# Infisical ClusterSecretStore Configuration
#
# SETUP STEPS:
# 1. Create a free Infisical account at https://app.infisical.com
# 2. Create a new project and note the "Project Slug" from project settings
# 3. Create a Machine Identity with Universal Auth:
#    - Go to Organization Settings > Machine Identities
#    - Create new identity, enable Universal Auth
#    - Copy the Client ID and Client Secret
# 4. Grant the Machine Identity access to your project
# 5. Create the credentials secret:
#    kubectl create namespace external-secrets
#    kubectl create secret generic infisical-credentials -n external-secrets \
#      --from-literal=clientId=<your-client-id> \
#      --from-literal=clientSecret=<your-client-secret>
#
# Then add your secrets in Infisical under the "dev" environment
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-secret-store
spec:
  provider:
    infisical:
      # Infisical Cloud API (default)
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-credentials
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-credentials
            namespace: external-secrets
      secretsScope:
        # Replace with your actual project slug from Infisical
        projectSlug: "homelab-secrets"
        environmentSlug: dev
        secretsPath: "/"

