# Chart: https://charts.gabe565.com/charts/adguard-home/

image:
  repository: adguard/adguardhome
  tag: v0.107.56
  pullPolicy: IfNotPresent

env:
  TZ: America/New_York 

service:
  main:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.242
    externalTrafficPolicy: Local
    annotations:
      # MetalLB allows these three Services to share the same external IP.
      metallb.universe.tf/allow-shared-ip: adguard
    ports:
      http:
        port: 3000

  dns-tcp:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.0.242
    externalTrafficPolicy: Local
    annotations:
      # MetalLB allows these three Services to share the same external IP.
      metallb.universe.tf/allow-shared-ip: adguard
    ports:
      dns-tcp:
        enabled: true
        port: 53
      dns-over-tls:
        enabled: false  # Disable DoT for simplicity in home setup
  # DNS UDP service  
  dns-udp:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 192.168.0.242
    externalTrafficPolicy: Local
    annotations:
      # MetalLB allows these three Services to share the same external IP.
      metallb.universe.tf/allow-shared-ip: adguard
    ports:
      dns-udp:
        enabled: true
        protocol: UDP
        port: 53
      dns-over-quic:
        enabled: false 
ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    hosts:
      - host: adguard.homelab
        paths:
          - path: /
            pathType: Prefix
    tls: []


persistence:
  config:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/conf
    accessMode: ReadWriteOnce
    size: 1Gi
  data:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/work
    accessMode: ReadWriteOnce
    size: 2Gi

# Initial AdGuard Home configuration
config: |
  bind_host: 0.0.0.0
  bind_port: 3000
  users: []
  auth_attempts: 5
  block_auth_min: 15
  http_proxy: ""
  language: "English"
  theme: auto
  debug_pprof: false
  web_session_ttl: 720
  dns:
    bind_hosts:
      - 0.0.0.0
    port: 53
    anonymize_client_ip: false
    protection_enabled: true
    blocking_mode: default
    blocking_ipv4: ""
    blocking_ipv6: ""
    blocked_response_ttl: 10
    parental_block_host: family-block.dns.adguard.com
    safebrowsing_block_host: standard-block.dns.adguard.com
    ratelimit: 20
    ratelimit_whitelist: []
    refuse_any: true
    upstream_dns:
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
    upstream_dns_file: ""
    bootstrap_dns:
      - 1.1.1.1
      - 8.8.8.8
    all_servers: false
    fastest_addr: false
    fastest_timeout: 1s
    allowed_clients: []
    disallowed_clients: []
    blocked_hosts:
      - version.bind
      - id.server
      - hostname.bind
    trusted_proxies:
      - 127.0.0.0/8
      - ::1/128
    cache_size: 4194304
    cache_ttl_min: 0
    cache_ttl_max: 0
    cache_optimistic: false
    bogus_nxdomain: []
    aaaa_disabled: false
    enable_dnssec: true
    edns_client_subnet:
      custom_ip: ""
      enabled: false
      use_custom: false
    max_goroutines: 300
    handle_ddr: true
    ipset: []
    ipset_file: ""
    filtering_enabled: true
    filters_update_interval: 24
    parental_enabled: false
    safesearch_enabled: false
    safebrowsing_enabled: false
    safebrowsing_cache_size: 1048576
    safesearch_cache_size: 1048576
    parental_cache_size: 1048576
    cache_time: 30
    rewrites:
      - domain: *.homelab 
        answer: 192.168.0.243
    blocked_services: []
    upstream_timeout: 10s
    private_networks: []
    use_private_ptr_resolvers: true
    local_ptr_upstreams: []
    serve_http3: false
    use_http3_upstreams: false
  tls:
    enabled: false
    server_name: ""
    force_https: false
    port_https: 443
    port_dns_over_tls: 853
    port_dns_over_quic: 784
    port_dnscrypt: 0
    dnscrypt_config_file: ""
    allow_unencrypted_doh: false
    certificate_chain: ""
    private_key: ""
    certificate_path: ""
    private_key_path: ""
    strict_sni_check: false
  filters:
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
      name: 1Hosts (Lite)
      id: 1
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
      name: AdGuard DNS filter
      id: 2
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_53.txt
      name: AWAvenue Ads Rule
      id: 3
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_59.txt
      name: AdGuard DNS Popup Hosts filter
      id: 4
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_51.txt
      name: HaGeZi's Pro++ Blocklist
      id: 5
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
      name: HaGeZi's Normal Blocklist
      id: 6
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
      name: Dan Pollock's List
      id: 7
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_48.txt
      name: HaGeZi's Pro Blocklist
      id: 8
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
      name: OISD Blocklist Small
      id: 9
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
      name: Malicious URL Blocklist (URLHaus)
      id: 10
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
      name: uBlock₀ filters – Badware risks
      id: 11
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
      name: OISD Blocklist Big
      id: 12
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
      name: The Big List of Hacked Malware Web Sites
      id: 13
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
      name: Peter Lowe's Blocklist
      id: 14
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
      name: Stalkerware Indicators List
      id: 15
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
      name: Steven Black's List
      id: 16
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_42.txt
      name: ShadowWhisperer's Malware List
      id: 17
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_45.txt
      name: HaGeZi's Allowlist Referral
      id: 18
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
      name: Scam Blocklist by DurableNapkin
      id: 19
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
      name: Dandelion Sprout's Game Console Adblock List
      id: 20
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt
      name: Phishing Army
      id: 21
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_39.txt
      name: Dandelion Sprout's Anti Push Notifications
      id: 22
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_56.txt
      name: HaGeZi's The World's Most Abused TLDs
      id: 23
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_47.txt
      name: HaGeZi's Gambling Blocklist
      id: 24
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_44.txt
      name: HaGeZi's Threat Intelligence Feeds
      id: 25
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_63.txt
      name: HaGeZi's Windows/Office Tracker Blocklist
      id: 26
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_52.txt
      name: HaGeZi's Encrypted DNS/VPN/TOR/Proxy Bypass
      id: 27
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_60.txt
      name: HaGeZi's Xiaomi Tracker Blocklist
      id: 28
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
      name: Phishing URL Blocklist (PhishTank and OpenPhish)
      id: 29
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_57.txt
      name: ShadowWhisperer's Dating List
      id: 30
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
      name: Dandelion Sprout's Anti-Malware List
      id: 31
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
      name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
      id: 32
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_54.txt
      name: HaGeZi's DynDNS Blocklist
      id: 33
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_55.txt
      name: HaGeZi's Badware Hoster Blocklist
      id: 34
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
      name: NoCoin Filter List
      id: 35
  whitelist_filters: []
  user_rules:
    - "||oslogs.umeng.com^$important"
    - "@@||o-sdk.mediation.unity3d.com^$important"
    - "@@||www.duckdns.org^$important"
  dhcp:
    enabled: false
  clients:
    runtime_sources:
      whois: true
      arp: true
      rdns: true
      dhcp: true
      hosts: true
    persistent: []
  log_file: ""
  log_max_backups: 0
  log_max_size: 100
  log_max_age: 3
  log_compress: false
  log_localtime: false
  verbose: false
  os:
    group: ""
    user: ""
    rlimit_nofile: 0
  schema_version: 20
