nameOverride: multus

image:
  repository: k8snetworkplumbingwg/multus-cni
  tag: latest-thick
  pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  create: true
  automountServiceAccountToken: true

hostCNIBinDir: /opt/cni/bin
hostCNINetDir: /etc/cni/net.d
