apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ollama
    repo: https://helm.otwld.com/
    version: 1.84.0
    releaseName: ollama
    namespace: ollama
    valuesFile: values.yaml

