apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: open-webui
    repo: https://helm.openwebui.com
    version: 16.6.0
    releaseName: open-webui
    namespace: open-web-ui
    valuesFile: values.yaml

