ollama:
  enabled: false

ollamaUrls:
  # in-cluster ollamna svc
  - "http://ollama.ollama:11434"

ingress:
  enabled: true
  class: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
  host: "chat.homelab"
  additionalHosts: []
  tls: false

persistence:
  enabled: true
  size: 5Gi