apiVersion: v1
kind: Service
metadata:
  name: ids-dev
  namespace: ids-system-dev
spec:
  type: ClusterIP
  selector:
    app: ids-dev
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
