apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: adguard-home
    repo: https://charts.gabe565.com
    version: 0.3.25
    releaseName: adguard
    namespace: adguard
    valuesFile: values.yaml

# Include resources from the old clusters structure
resources:
  - namespace.yaml