apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gha-runner-scale-set-controller
    repo:  oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.14.2
    releaseName: arc
    namespace: gha-runner-controller
    valuesFile: values.yaml
    