apiVersion: hermes.agent/v1alpha1
kind: HermesInstance
metadata:
  name: homelab-agent
spec:
  provider: openai
  baseUrl: "http:/ollama.ollama:11434/v1" 
  model: "nous-hermes2" 
  envFrom:
    - secretRef:
        name: hermes-homelab-secrets
  webUI:
    enabled: true
    port: 8780