apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - secret-sealed.yaml
  - service.yaml
  - hermes-instance.yaml

helmCharts:
  - name: hermes-operator
    repo: oci://ghcr.io/paperclipinc/charts
    version: 0.2.0
    releaseName: hermes-operator
    namespace: hermes-operator
    valuesFile: values.yaml