---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-homelab-secrets
  namespace: kata-system
spec:
  encryptedData:
    OPENAI_API_KEY: AgAhToesvjMZwdTV0szrgU0fJariOikUZS96smVeJVvipUwrU9YOwW0XCM/RlcNNrv5NcmrD/M8isVcSc+EqgAwAfyyqKdJexFzl7FYxvtOXOf30tHyur2DEFbnlTgMSAa/+l9LIRYj392algziNKVCxszsi7YeMiDLiE9P8NmNJSN1pwcrF4CwxvR9hFhKl1Cu3b1d6XtxrBZGAzXXOktrSzmCWkEVPrcFVCejLabhMswZ6pIHUt7+AfedqHEBEMB8I+D0388/ncIWtS7n5mZXBgGzFnNYaa57Snqo0R5hmYgfDMvcUNay4mxvH1B01c/wbBoDPE12aMNqwE3nr/sVTUIHQU+lC+W/PFkO3rwwP3lURNZ+StrD7i3LCCT2wvk2fcyxyBgiYJR81zgWQMRFzuxRlyA0MVEGDGEJrM+7XnSb/JVgk1aYm1xmG0E8TSZdkvHY2hpqydS/MxYsgelUedud0XJpq76Gdc9+ApIeEzbOVZSbktHApmXcp7brrtScEsogGz0rjk/L3FnvklirwyXK9/e1vOsPG/IbRBwEcCKVAg8sb3uj7l4DyHeJGf6j0EI3xd3BknSkh/esGSeHkQNKbDHGRqC3N/D2AvOC0tdPTlEA7X7d9hMvqRMVCvdTtG2p15LWk02woTpkIe6YN6RMPXBQtNrhbAPQDYm9p9Aqt/lYC8QlhY2a9S84MgaIXcQOXIv780iYr175831I=
    WEBUI_PASSWORD: AgCSQrJjNcNkbG4bcFmLvHIXno3dTH0/AbMSHZuD7qEYLDMH7bQJp3uLWpUBToy5xYMBpd3mHDeisqGAq8lyEWqv6j03xBnUTCWa5UUJcm+ficwAijJxVya9HSzYzNDJYD4yuUmchHAQcCsjXQbzVt1GIz8e1uyCCWiSQmKFVGX+uVPo1+bEGCPDqJQdDVunXdRyLo8euISZtkBgmcTL3kXY103oyDHZdDfnN0XEYRCGXAa3SZq1FwKYqaqu8NZvoORFGtsIM4tqq+R63p+TQiWAHc5GHEvzuwtf3UNkkrVGjCx0ltpNxXPdMunyBvCdOpq5/KC+WKzUicZQuNFJUjs4teyagBkJgeTQDT8RlHdLDPS/IEZEFNVjSAa8H9ESEchz7NDMC0bSXZDQfcJMjzFLg7Q+147uc/Q4F8ZmqEyrFy+4eiBSUojU689kkoPlWgEEQFkoU5eXsUHWSKhLraxZy1EkX2+j1dmPS3QUKK4g3BcaxJWyRr+NIoNJYTqGocwEFwxFw35skaYRq0gSza+dwRcVBVgffTO0Xv+Wz92UCTiMUXQZZPUSHXj9lPuimQIIA9Aj3XZm7rj3fD8QgUwxrYp9kTJhVIVSI8Btt30bbYTjV/TZTnrRvpz5FZJbn2XPQalEhr33NYrIjEoB3colY+NK05bP4Dn4vwVGkPK1tiFu/bRfVKHQ+JDSMkfW6bBsCSA=
  template:
    metadata:
      name: hermes-homelab-secrets
      namespace: kata-system
    type: Opaque
