# apps/ingress-nginx/overlays/prod/service-patch.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default-pool
    metallb.universe.tf/loadBalancerIPs: "10.0.0.11"
spec:
  type: LoadBalancer