apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: homelab
  annotations:
    managed-by: argocd
type: Opaque
stringData:
  name: homelab
  server: https://kubernetes.default.svc
